# fly.toml for Web service
app = 'scripter-tool-system-web'
primary_region = 'lhr'

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1

[env]
  VITE_API_BASE = "https://scripter-tool-system-api.fly.dev"
